import { stat } from "node:fs/promises";
import { isAbsolute } from "node:path";
import type { Logger } from "pino";
import { Check } from "typebox/value";
import {
	TranscodeAudioSchema,
	TranscodeVideoSchema,
} from "../../contracts/schemas/transcode-profiles.js";
import type { DeepReadonly } from "../../shared/policy.js";
import { MediaOutputBudgetError, MediaToolError } from "./errors.js";
import type { MediaInfo, MediaProcessingOptions, ToolStatus } from "./model.js";
import { type MediaToolPolicy, mediaToolPolicy } from "./policy.js";
import { startMediaProcess } from "./processing-process.js";

/** Compile only typed profile settings and application-generated filters. */
export function compileFfmpegArguments(
	input: string,
	output: string,
	options: MediaProcessingOptions,
): string[] {
	const { plan } = options;
	if (
		![input, output].every(
			(path) => isAbsolute(path) && !path.includes("\0"),
		) ||
		input === output ||
		!Number.isSafeInteger(options.maximumBytes) ||
		options.maximumBytes <= 0 ||
		!Number.isSafeInteger(options.videoStreamIndex) ||
		options.videoStreamIndex < 0 ||
		(options.audioStreamIndex !== null &&
			(!Number.isSafeInteger(options.audioStreamIndex) ||
				options.audioStreamIndex < 0))
	)
		throw new MediaToolError(
			"INVALID_INPUT",
			"Invalid FFmpeg paths, stream selection or output budget.",
		);
	if (!["mp4", "mov", "matroska", "webm"].includes(plan.container))
		throw new MediaToolError(
			"INVALID_INPUT",
			"Unsupported FFmpeg delivery container.",
		);
	const args = [
		"-nostdin",
		"-hide_banner",
		"-v",
		"error",
		"-n",
		"-progress",
		"pipe:1",
		"-nostats",
		"-protocol_whitelist",
		"file,pipe",
		"-i",
		input,
		"-map",
		`0:${options.videoStreamIndex}`,
		"-map_metadata",
		"-1",
		"-map_chapters",
		"-1",
		"-sn",
		"-dn",
	];
	if (plan.video.action === "copy") {
		if (plan.videoParameters || plan.videoFilters?.length || plan.h264Level)
			throw new MediaToolError(
				"INVALID_INPUT",
				"Copied video cannot have encoding settings.",
			);
		args.push("-c:v", "copy");
	} else {
		const video = plan.videoParameters;
		if (
			!video ||
			!Check(TranscodeVideoSchema, video) ||
			video.encoder !== plan.video.encoder ||
			video.codec !== plan.video.codec ||
			video.pixelFormat !== plan.video.pixelFormat
		)
			throw new MediaToolError(
				"INVALID_INPUT",
				"Video encoding requires matching typed parameters.",
			);
		args.push("-c:v", video.encoder, "-pix_fmt", video.pixelFormat);
		if ("crf" in video) args.push("-crf", String(video.crf));
		if ("preset" in video) args.push("-preset", String(video.preset));
		if ("cpuUsed" in video)
			args.push("-cpu-used", String(video.cpuUsed), "-b:v", "0");
		if ("bitrateKbps" in video) args.push("-b:v", `${video.bitrateKbps}k`);
		if (plan.h264Level) {
			if (
				plan.h264Level !== "5.1" ||
				video.encoder !== "libx264" ||
				video.pixelFormat !== "yuv420p"
			)
				throw new MediaToolError(
					"INVALID_INPUT",
					"Unsupported H.264 output descriptor.",
				);
			args.push("-profile:v", "high", "-level:v", plan.h264Level);
		}
		if (plan.videoFilters?.length) {
			// No arbitrary graphs: match the expressions generated by the resolver.
			if (
				!plan.videoFilters.every((filter) =>
					/^scale=w=-2:h=\d+:flags=lanczos$|^pad=ceil\(iw\/2\)\*2:ceil\(ih\/2\)\*2$|^format=[a-z][a-z0-9_]{0,63}$/.test(
						filter,
					),
				)
			)
				throw new MediaToolError(
					"INVALID_INPUT",
					"Unsupported generated video filter.",
				);
			args.push("-vf", plan.videoFilters.join(","));
		}
	}
	const dependencies = [
		...(plan.video.action === "encode"
			? [
					"buffer",
					"buffersink",
					"null",
					"scale",
					...(plan.videoFilters ?? []).map(
						(filter) => filter.split("=")[0] as string,
					),
				]
			: []),
		...(options.audioStreamIndex !== null && plan.audio.action === "encode"
			? ["abuffer", "abuffersink", "aresample", "aformat", "anull"]
			: []),
	];
	if (dependencies.some((filter) => !plan.filters.includes(filter)))
		throw new MediaToolError(
			"INVALID_INPUT",
			"Execution plan omits required conversion filters.",
		);
	if (options.audioStreamIndex === null) args.push("-an");
	else {
		args.push("-map", `0:${options.audioStreamIndex}`);
		if (plan.audio.action === "copy") {
			if (plan.audioParameters)
				throw new MediaToolError(
					"INVALID_INPUT",
					"Copied audio cannot have encoding settings.",
				);
			args.push("-c:a", "copy");
		} else {
			const audio = plan.audioParameters;
			if (
				!audio ||
				!Check(TranscodeAudioSchema, audio) ||
				audio.encoder !== plan.audio.encoder ||
				audio.codec !== plan.audio.codec
			)
				throw new MediaToolError(
					"INVALID_INPUT",
					"Audio encoding requires matching typed parameters.",
				);
			args.push("-c:a", audio.encoder);
			if (audio.encoder === "aac") args.push("-profile:a", "aac_low");
			if ("bitrateKbps" in audio) args.push("-b:a", `${audio.bitrateKbps}k`);
			if ("compressionLevel" in audio)
				args.push("-compression_level", String(audio.compressionLevel));
			if (audio.channels === "stereo") args.push("-ac", "2");
		}
	}
	if (plan.delivery === "media-source") {
		if (plan.container !== "mp4")
			throw new MediaToolError(
				"INVALID_INPUT",
				"Fragmented delivery currently requires MP4.",
			);
		args.push("-movflags", "+frag_keyframe+empty_moov+default_base_moof");
	} else if (plan.delivery !== undefined && plan.delivery !== "file") {
		throw new MediaToolError("INVALID_INPUT", "Invalid delivery target.");
	} else if (plan.container === "mp4" || plan.container === "mov")
		args.push("-movflags", "+faststart");
	args.push("-fs", String(options.maximumBytes), "-f", plan.container, output);
	return args;
}

/** Local complete-file adapter. Publication and source checks belong to the application. */
export class FfmpegExecutionAdapter {
	constructor(
		private readonly ffmpeg: ToolStatus,
		private readonly policy: DeepReadonly<MediaToolPolicy> = mediaToolPolicy,
		private readonly logger?: Logger,
	) {}
	async execute(
		input: string,
		output: string,
		options: MediaProcessingOptions,
		info: MediaInfo,
	): Promise<void> {
		if (!this.ffmpeg.available)
			throw new MediaToolError("TOOL_UNAVAILABLE", this.ffmpeg.message);
		if (!isAbsolute(this.ffmpeg.path))
			throw new MediaToolError(
				"INVALID_INPUT",
				"FFmpeg must be a resolved executable.",
			);
		options.signal?.throwIfAborted();
		if (!(await stat(input)).isFile())
			throw new MediaToolError(
				"INVALID_INPUT",
				"FFmpeg input must be a regular file.",
			);
		const args = compileFfmpegArguments(input, output, options);
		const child = startMediaProcess(
			this.ffmpeg.path,
			args,
			{
				...(options.signal ? { signal: options.signal } : {}),
				timeoutMs: options.timeoutMs,
				durationMs:
					info.duration && info.duration > 0 ? info.duration * 1000 : null,
				...(options.onEvent ? { onEvent: options.onEvent } : {}),
			},
			this.policy,
			this.logger,
		);
		await child.completion;
		options.signal?.throwIfAborted();
		const size = (await stat(output)).size;
		if (size >= options.maximumBytes) throw new MediaOutputBudgetError();
		if (size <= 0)
			throw new MediaToolError(
				"TOOL_FAILED",
				"FFmpeg output is empty or exceeds the output budget.",
			);
	}
}
